FROM node:22-bullseye
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm install --omit=dev
COPY dist ./dist
COPY src ./src
COPY apps ./apps
COPY web ./web
COPY data ./data
CMD ["npm", "run", "start:ssr"]
